# Generated by Django 5.0.2 on 2024-03-03 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('level', models.DecimalField(decimal_places=0, max_digits=2)),
                ('location', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hire_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='market_salary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=0, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rating',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='increase_suggestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('suggestion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewdb.rating')),
            ],
            options={
                'db_table': 'increase_suggestion',
                'ordering': ['-created_at'],
            },
        ),
    ]
