# Generated by Django 5.0.2 on 2024-03-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewdb', '0002_employee_currency_employee_currency_currency_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='increase_suggestion',
            new_name='IncreaseSuggestion',
        ),
        migrations.RenameModel(
            old_name='market_salary',
            new_name='MarketSalary',
        ),
    ]
