# Generated by Django 5.0.2 on 2024-03-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewdb', '0003_rename_increase_suggestion_increasesuggestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='currency_currency',
        ),
        migrations.AlterField(
            model_name='employee',
            name='currency',
            field=models.CharField(default='SEK', max_length=100),
        ),
    ]
