# Generated by Django 5.0.2 on 2024-06-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewdb', '0004_remove_employee_currency_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataset_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schema', models.JSONField()),
            ],
            options={
                'db_table': 'dataset_list',
                'ordering': ['-created_at'],
            },
        ),
    ]
