# Generated by Django 5.0.2 on 2024-06-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewdb', '0005_datasetlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetlist',
            name='schema',
        ),
        migrations.RemoveField(
            model_name='datasetlist',
            name='updated_at',
        ),
    ]
